//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Animals1 = new HashSet<Animal>();
            this.Animals11 = new HashSet<Animal>();
            this.events = new HashSet<@event>();
        }
    
        public int id { get; set; }
        public string ear_tag { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public System.DateTime birth_date { get; set; }
        public Nullable<int> breed { get; set; }
        public string origin { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public Nullable<int> mother_id { get; set; }
        public Nullable<int> father_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string status { get; set; }
    
        public virtual AnimalGroup AnimalGroup { get; set; }
        public virtual breed breed1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals1 { get; set; }
        public virtual Animal Animal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals11 { get; set; }
        public virtual Animal Animal2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> events { get; set; }
    }
}
