//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimalGroup()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public int id { get; set; }
        public int idType { get; set; }
        public int idRoom { get; set; }
        public int idEmployee { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual room room { get; set; }
        public virtual groupType groupType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
