//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.AnimalGroups = new HashSet<AnimalGroup>();
            this.EventEmployees = new HashSet<EventEmployee>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string midleName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public System.DateTime birthday { get; set; }
        public string pasport { get; set; }
        public string snils { get; set; }
        public string inn { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int idpost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalGroup> AnimalGroups { get; set; }
        public virtual post post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventEmployee> EventEmployees { get; set; }
    }
}
