//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEmployee
    {
        public int eventId { get; set; }
        public int employeeId { get; set; }
        public string description { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual @event @event { get; set; }
    }
}
