//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fermEntities : DbContext
    {
        public fermEntities()
            : base("name=fermEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalGroup> AnimalGroups { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<breed> breeds { get; set; }
        public virtual DbSet<counterparty> counterparties { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<EventEmployee> EventEmployees { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<groupType> groupTypes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productShipment> productShipments { get; set; }
        public virtual DbSet<productType> productTypes { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<roomType> roomTypes { get; set; }
        public virtual DbSet<shipment> shipments { get; set; }
    
        public virtual int addNewRoomType(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addNewRoomType", nameParameter);
        }
    }
}
