//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productShipment
    {
        public int idProduct { get; set; }
        public int idShipment { get; set; }
        public int quantity { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual product product { get; set; }
        public virtual shipment shipment { get; set; }
    }
}
