//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.productShipments = new HashSet<productShipment>();
        }
    
        public int id { get; set; }
        public int quantity { get; set; }
        public string descriiption { get; set; }
        public int idType { get; set; }
        public System.DateTime prodauctionDate { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int idEvent { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual productType productType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productShipment> productShipments { get; set; }
    }
}
