//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pigFermEntities : DbContext
    {
        public pigFermEntities()
            : base("name=pigFermEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animalGroup> animalGroups { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<breed> breeds { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<groupType> groupTypes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<roomType> roomTypes { get; set; }
        public virtual DbSet<feed> feeds { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
