//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pigFerm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.animalGroups = new HashSet<animalGroup>();
        }
    
        public int id { get; set; }
        public string adres { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> currentCount { get; set; }
        public string locationNotes { get; set; }
        public Nullable<int> typeRoom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<animalGroup> animalGroups { get; set; }
        public virtual roomType roomType { get; set; }
    }
}
